### ISSUE TITLE
get_rate missing 'dest_cur'

### ISSUE THREAD

**Issue by fornakter** [MicroPyramid/forex-python#116]
Im try to use forex-python and recive an error:
TypeError: get_rate() missing 1 required positional argument: 'dest_cur'
CODE:
`from forex_python.converter import CurrencyRates
c = CurrencyRates

print(c.get_rate('USD', 'GBP'))`

**Comment by leozitor** [comment]
try 

```python
c = CurrencyRates()

print(c.get_rate('USD', 'GBP'))
```

**Comment by MJ-Kim-dev** [comment]
Same issue for me. 

>>> c = CurrencyRates()
>>> c.get_rate('USD')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_rate() missing 1 required positional argument: 'dest_cur'
>>> 
>>> print(c.get_rate('usd'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_rate() missing 1 required positional argument: 'dest_cur'
>>> print(c.get_rate('USD', 'CAD'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/env/lib/python3.8/site-packages/forex_python/converter.py", line 74, in get_rate
    rate = self._get_decoded_rate(response, dest_cur, date_str=date_str)
  File "/home/ubuntu/env/lib/python3.8/site-packages/forex_python/converter.py", line 47, in _get_decoded_rate
    return self._decode_rates(
  File "/home/ubuntu/env/lib/python3.8/site-packages/forex_python/converter.py", line 40, in _decode_rates
    decoded_data = response.json()
  File "/home/ubuntu/env/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/env/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/ubuntu/env/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ashwin31** [comment]
Thank you @leozitor
