### ISSUE TITLE
RatesNotAvailableError: Currency Rates Source Not Ready

### ISSUE THREAD

**Issue by TiagONTOP** [MicroPyramid/forex-python#135]
Hello everyone,

I use this module in my trading bot and starting from today, I've been encountering an error. I noticed from the code that the issue seems to stem from the "freeforexapi" which is returning a status code different from 200. Below is the error that I'm encountering in the terminal:

[LightGBM] [Warning] feature_fraction is set=0.1, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.1
[LightGBM] [Warning] bagging_fraction is set=0.3, subsample=1.0 will be ignored. Current value: bagging_fraction=0.3
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
Traceback (most recent call last):
  File "c:\Users\ftiag\Desktop\Business, trading et investissement\Business\strategie trading\Recherche FTMO\HFT_FTMO_ALLPAIRS\TradingBOT\TradingBOT\run_robot.py", line 90, in <module>
    brk.create_entry_trades(dict_pos=tickers_to_trade)
  File "C:\Users\ftiag\Desktop\Business, trading et investissement\Business\strategie trading\Recherche FTMO\HFT_FTMO_ALLPAIRS\TradingBOT\TradingBOT\pyrobot\broker.py", line 81, in create_entry_trades
    "volume" : self.leverage_to_volume(ticker),
  File "C:\Users\ftiag\Desktop\Business, trading et investissement\Business\strategie trading\Recherche FTMO\HFT_FTMO_ALLPAIRS\TradingBOT\TradingBOT\pyrobot\broker.py", line 127, in leverage_to_volume
    lot_value = self.cr.convert(currency_base, account_currency, account)
  File "C:\Users\ftiag\anaconda3\lib\site-packages\forex_python\converter.py", line 108, in convert
    raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready
PS C:\Users\ftiag\Desktop\Business, trading et investissement\Business\strategie trading\Recherche FTMO\HFT_FTMO_ALLPAIRS\TradingBOT>

**Comment by lfwcaspersen** [comment]
I am getting the same issue at the moment for code that was running fine yesterday. It appears that the python-forex api site is just down.

**Comment by Jannickz** [comment]
Getting the same error since yesterday... would this be fixed..? T^T

**Comment by jpcorbeil-nuance** [comment]
same issue here

**Comment by ashwin31** [comment]
fixed
