### ISSUE TITLE
Having trouble in retriving information from api - may not be bug

### ISSUE THREAD

**Issue by SantoshParit** [MicroPyramid/forex-python#20]
I have a following issue, when I try to get currency rates : 
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    c.get_rates('USD')
  File "C:\Python27\lib\site-packages\forex_python\converter.py", line 34, in get_rates
    source_url = self._source_url() + date_str
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='api.fixer.io', port=80): Max retries exceeded with url: /latest?base=USD (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03175790>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

I am using : 
requests : https://github.com/kennethreitz/requests/releases/tag/v2.13.0
forex-python : https://github.com/MicroPyramid/forex-python/releases/tag/0.3.0

**Comment by ravigadila** [comment]
I don't have above issue.

```
# forex-python (0.3.0)
In [3]: c.get_rates('USD')
Out[3]: 
{'AUD': 1.3266, 'BGN': 1.8311, 'BRL': 3.1677, 'CAD': 1.3119.........}
 ```
Do you still have same issue?

**Comment by SantoshParit** [comment]
I still have the same issue, :-(
