### ISSUE TITLE
Converting to same currency yields error

### ISSUE THREAD

**Issue by Atnas1010** [MicroPyramid/forex-python#24]
When I try to convert euro to euro I get an error

`c.convert('EUR', 'EUR', 1)`
```
Traceback (most recent call last):
  File "<ipython-input-166-826503d53e1f>", line 1, in <module>
    c.convert('eur', 'eur', 1)
  File "c:\python35\lib\site-packages\forex_python\converter.py", line 84, in convert
    source_url, dest_cur, date_str))
RatesNotAvailableError: Currency http://api.fixer.io/latest => eur rate not available for Date latest.

```
I'm not sure if this is intentional, but it would make my code cleaner if it just returned the same value.

**Comment by ravigadila** [comment]
@Atnas1010 issue fixed in master.
