### ISSUE TITLE
pip install forex-python under Python 3.6.8 in failing on mac os x

### ISSUE THREAD

**Issue by ThomasSYT** [MicroPyramid/forex-python#55]
Hi,
Today, I tried to install forex_python using pip, but failed: 
Collecting forex_python
Requirement already satisfied: requests in /anaconda3/lib/python3.6/site-packages (from forex_python) (2.18.4)
Collecting dbus-python (from forex_python)
  Using cached https://files.pythonhosted.org/packages/3f/e7/4edb582d1ffd5ac3c84188deea32e960b5c8c0fe1da56ce70224f85ce542/dbus-python-1.2.8.tar.gz
Requirement already satisfied: simplejson in /anaconda3/lib/python3.6/site-packages (from forex_python) (3.16.0)
Requirement already satisfied: notify2 in /anaconda3/lib/python3.6/site-packages (from forex_python) (0.3.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.6/site-packages (from requests->forex_python) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.6/site-packages (from requests->forex_python) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.6/site-packages (from requests->forex_python) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.6/site-packages (from requests->forex_python) (2018.11.29)
Building wheels for collected packages: dbus-python
  Building wheel for dbus-python (setup.py) ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-wheel-3s_dwtm4 --python-tag cp36:
  running bdist_wheel
  running build
  creating /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build
  creating /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build/temp.macosx-10.7-x86_64-3.6
  checking whether make supports nested variables... no
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for gcc... gcc
  checking whether the C compiler works... no
  configure: error: in `/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build/temp.macosx-10.7-x86_64-3.6':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py", line 109, in <module>
      tests_require=['tap.py'],
    File "/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py", line 62, in run
      cwd=builddir)
    File "/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/anaconda3/bin/python', '--prefix=/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build/temp.macosx-10.7-x86_64-3.6/prefix']' returned non-zero exit status 77.
  
  ----------------------------------------
  Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: dbus-python, forex-python
  Running setup.py install for dbus-python ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-record-17_xhgd1/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build
    creating /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build/temp.macosx-10.7-x86_64-3.6
    checking whether make supports nested variables... no
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build/temp.macosx-10.7-x86_64-3.6':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/anaconda3/bin/python', '--prefix=/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/build/temp.macosx-10.7-x86_64-3.6/prefix']' returned non-zero exit status 77.
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-record-17_xhgd1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/4l/phzz7lg162bdp43zvngkzf500000gn/T/pip-install-d528248k/dbus-python/

Please help, thanks.

**Comment by pnhofmann** [comment]
python-dbus needs native C extension - which fail on your PC. Look [here](https://anaconda.org/conda-forge/dbus) how to install python-dbus for anaconda.

But since python-dbus isn't a requirement any (see #56) forex-python==1.3 should install with no error. Guess this can be closed now, too?

**Comment by ThomasSYT** [comment]
> python-dbus needs native C extension - which fail on your system. Look [here](https://anaconda.org/conda-forge/dbus) how to install python-dbus for anaconda.
> 
> But since python-dbus isn't a requirement any (see #56) forex-python==1.3 should install with no error. Guess this can be closed now, too?



> python-dbus needs native C extension - which fail on your system. Look [here](https://anaconda.org/conda-forge/dbus) how to install python-dbus for anaconda.
> 
> But since python-dbus isn't a requirement any (see #56) forex-python==1.3 should install with no error. Guess this can be closed now, too?

Thanks a lot! It works now.
