### ISSUE TITLE
API doesn't work on 2020/Mar/5

### ISSUE THREAD

**Issue by qmhedging** [MicroPyramid/forex-python#77]
API doesn't work on 2020/Mar/5

it stuck in running and no exchange rate result returned.

Worked ok on previous days.

**Comment by qmhedging** [comment]
after long waiting, it will return some error code:

Traceback (most recent call last):
  Python Shell, prompt 7, line 1
  File "e:\Python37\Lib\site-packages\forex_python\converter.py", line 58, in get_rate
    def get_rate(self, base_cur, dest_cur, date_obj=None):
  File "e:\Python37\Lib\site-packages\requests\api.py", line 64, in get
    def get(url, params=None, **kwargs):
  File "e:\Python37\Lib\site-packages\requests\api.py", line 16, in request
    def request(method, url, **kwargs):
  File "e:\Python37\Lib\site-packages\requests\sessions.py", line 463, in request
    def request(self, method, url,
  File "e:\Python37\Lib\site-packages\requests\sessions.py", line 614, in send
    def send(self, request, **kwargs):
  File "e:\Python37\Lib\site-packages\requests\adapters.py", line 394, in send
    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
